version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: 'node_app'    
    ports:
      - 3306:3306
  node_app:
    image: shah06/node_app
    container_name: node_app
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:8080
